# hadolint ignore=DL3006
FROM adoptopenjdk/openjdk11
RUN mkdir /usr/src/scripts

EXPOSE 8080

ARG VERSION
ENV VERSION_ENV=${VERSION}

RUN groupadd -r func_user && useradd -r -s /bin/false -g func_user func_user
WORKDIR /usr/src/app/

COPY monitor/target/monitor-${VERSION}.jar /usr/src/app

USER func_user
CMD ["sh", "-c", "java ${JAVA_OPTS} -jar monitor-${VERSION_ENV}.jar"]