global:
  imageCredentials:
    pullPolicy: Never
  registry:
    url: null
    pullSecret: null
  istio:
    sidecar:
      inject: true
  timezone: "UTC"
  services:
    kafka:
      hostname: message-bus-kafka
      port: 9092
    zookeeper:
      hostname: zookeeper
      port: 2181

replicaCount: 2

imageCredentials:
  repoPath: proj-coinbase
  pullPolicy: Never
  registry:
    url: localhost:5000
    pullSecret: null

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 128Mi

nameOverride: