apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "istio-config.name" . }}-config-reader
  labels:
    {{- include "istio-config.helm-labels" . | indent 4 }}
  annotations:
    {{- include "istio-config.product-info" . | indent 4 }}
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - services
      - endpoints
      - configmaps
      - secrets
      - statefulsets
    verbs:
      - get
      - watch
      - list