apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "istio-config.name" . }}
  labels:
    {{- include "istio-config.helm-labels" . | indent 4 }}
  annotations:
    {{- include "istio-config.product-info" . | indent 4 }}
