apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coinbase-client.name" . }}
  labels:
    {{- include "coinbase-client.helm-labels" . | indent 4 }}
  annotations:
    {{- include "coinbase-client.product-info" . | indent 4 }}
