apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.services.kafka.hostname }}
  labels:
    {{- include "message-bus-kafka.helm-labels" . | indent 4 }}
  annotations:
    {{- include "message-bus-kafka.product-info" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.global.services.kafka.port }}
      name: kafka-client
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ template "message-bus-kafka.name" . }}