apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "coinbase-client.name" . }}
  labels:
    {{- include "coinbase-client.helm-labels" . | indent 4 }}
  annotations:
    {{- include "coinbase-client.product-info" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "coinbase-client.name" . }}-config-reader
subjects:
  - kind: ServiceAccount
    name: {{ template "coinbase-client.name" . }}
    namespace: {{ .Release.namespace }}