apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "istio-config.name" . }}-cluster-admin
  labels:
    {{- include "istio-config.helm-labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install, post-install, pre-upgrade, post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ template "istio-config.name" . }}
    namespace: {{ .Release.Namespace }}