apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "coinbase-monitor.name" . }}
  labels:
    app: {{ template "coinbase-monitor.name" . }}
    release: {{ .Release.Name }}
    {{- include "coinbase-monitor.helm-labels" . | indent 4 }}
  annotations:
    {{- include "coinbase-monitor.product-info" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
  minReadySeconds: 0

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "coinbase-monitor.name" . }}

  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: {{ quote .Values.global.istio.sidecar.inject }}
        {{- include "coinbase-monitor.product-info" . | indent 8 }}
      labels:
        {{- include "coinbase-monitor.helm-labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "coinbase-monitor.name" . }}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "coinbase-monitor.name" . }}
                topologyKey: kubernetes.io/hostname
      containers:
        - name: {{ template "coinbase-monitor.name" . }}
          image: "{{ default .Values.global.registry.url .Values.imageCredentials.registry.url }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.images.coinbaseMonitor.name }}:{{ .Values.images.coinbaseMonitor.tag }}"
          env:
            - name: CONTAINER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "coinbase-monitor.name" . }}
                  key: jvm.java_opts
            - name: SERVICE_NAME
              value: {{ include "coinbase-monitor.name" . }}
            - name: KUBERNETES_SERVICE_HOST
              value: kubernetes.default.svc
            - name: TZ
              value: {{ .Values.global.timezone }}
          imagePullPolicy: {{ default .Values.global.imageCredentials.pullPolicy .Values.imageCredentials.pullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
            periodSeconds: {{ .Values.app.internal.livenessTimeoutSeconds }}
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 10
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: {{ template "coinbase-monitor.name" . }}-cm-volume
              mountPath: /etc/config
      volumes:
        - name: {{ template "coinbase-monitor.name" . }}-cm-volume
          configMap:
            name: {{ template "coinbase-monitor.name" . }}