apiVersion: v1
kind: Service
metadata:
  name: {{ template "coinbase-monitor.name" . }}
  labels:
    {{- include "coinbase-monitor.helm-labels" . | indent 4 }}
  annotations:
    {{- include "coinbase-monitor.product-info" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ template "coinbase-monitor.name" . }}
  selector:
    app.kubernetes.io/name: {{ template "coinbase-monitor.name" . }}