kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "mongo.name" . }}
  labels:
    app: {{ template "mongo.name" . }}
    release: {{ .Release.Name }}
    {{- include "mongo.helm-labels" . | indent 4 }}
  annotations:
    {{- include "mongo.product-info" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "mongo.name" . }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: {{ quote .Values.global.istio.sidecar.inject }}
        {{- include "mongo.product-info" . | indent 8 }}
      labels:
        {{- include "mongo.helm-labels" . | indent 8 }}
    spec:
      restartPolicy: Always
      volumes:
        - name: {{ template "mongo.name" . }}
          persistentVolumeClaim:
            claimName: {{ template "mongo.name" . }}
      containers:
        - name: mongodb-container
          image: mongo
          volumeMounts:
            - name: {{ template "mongo.name" . }}
              mountPath: /var/lib/mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 27017
        - name: mongo-express
          image: mongo-express
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"
            - name: ME_CONFIG_MONGODB_SERVER
              value: "localhost"
          ports:
            - containerPort: 8081