apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "mongo.name" . }}
  labels:
    app: {{ template "mongo.name" . }}
    release: {{ .Release.Name }}
    {{- include "mongo.helm-labels" . | indent 4 }}
  annotations:
    {{- include "mongo.product-info" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mongoData